//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZLab_Analyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZLab_Analyzer.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Back ähnelt.
        /// </summary>
        internal static string button_back {
            get {
                return ResourceManager.GetString("button_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel file ähnelt.
        /// </summary>
        internal static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Create export ähnelt.
        /// </summary>
        internal static string button_create {
            get {
                return ResourceManager.GetString("button_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Done ähnelt.
        /// </summary>
        internal static string button_done {
            get {
                return ResourceManager.GetString("button_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Exit application ähnelt.
        /// </summary>
        internal static string button_exit {
            get {
                return ResourceManager.GetString("button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Next ähnelt.
        /// </summary>
        internal static string button_next {
            get {
                return ResourceManager.GetString("button_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die inner circle ähnelt.
        /// </summary>
        internal static string chart_2circle_combinedlegend_inner {
            get {
                return ResourceManager.GetString("chart_2circle_combinedlegend_inner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die outer circle ähnelt.
        /// </summary>
        internal static string chart_2circle_combinedlegend_outer {
            get {
                return ResourceManager.GetString("chart_2circle_combinedlegend_outer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fast movement: lardur ähnelt.
        /// </summary>
        internal static string chart_2circle_subtitle_fast {
            get {
                return ResourceManager.GetString("chart_2circle_subtitle_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no movement: inadur ähnelt.
        /// </summary>
        internal static string chart_2circle_subtitle_inactive {
            get {
                return ResourceManager.GetString("chart_2circle_subtitle_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die slow movement: smldur ähnelt.
        /// </summary>
        internal static string chart_2circle_subtitle_slow {
            get {
                return ResourceManager.GetString("chart_2circle_subtitle_slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die time spent in inner and outer circle ähnelt.
        /// </summary>
        internal static string chart_2circle_title_combined {
            get {
                return ResourceManager.GetString("chart_2circle_title_combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die time spent in inner circle ähnelt.
        /// </summary>
        internal static string chart_2circle_title_inner {
            get {
                return ResourceManager.GetString("chart_2circle_title_inner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die time spent in outer circle ähnelt.
        /// </summary>
        internal static string chart_2circle_title_outer {
            get {
                return ResourceManager.GetString("chart_2circle_title_outer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die records ähnelt.
        /// </summary>
        internal static string chart_2circle_title_xaxis {
            get {
                return ResourceManager.GetString("chart_2circle_title_xaxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die time spent % ähnelt.
        /// </summary>
        internal static string chart_2circle_title_yaxis {
            get {
                return ResourceManager.GetString("chart_2circle_title_yaxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die inactive ähnelt.
        /// </summary>
        internal static string chart_animals_result_0 {
            get {
                return ResourceManager.GetString("chart_animals_result_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die slow ähnelt.
        /// </summary>
        internal static string chart_animals_result_1 {
            get {
                return ResourceManager.GetString("chart_animals_result_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fast ähnelt.
        /// </summary>
        internal static string chart_animals_result_2 {
            get {
                return ResourceManager.GetString("chart_animals_result_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not detected ähnelt.
        /// </summary>
        internal static string chart_animals_result_3 {
            get {
                return ResourceManager.GetString("chart_animals_result_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die inactive ähnelt.
        /// </summary>
        internal static string chart_animals_unfiltered_0 {
            get {
                return ResourceManager.GetString("chart_animals_unfiltered_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die slow ähnelt.
        /// </summary>
        internal static string chart_animals_unfiltered_1 {
            get {
                return ResourceManager.GetString("chart_animals_unfiltered_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fast ähnelt.
        /// </summary>
        internal static string chart_animals_unfiltered_2 {
            get {
                return ResourceManager.GetString("chart_animals_unfiltered_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not detected ähnelt.
        /// </summary>
        internal static string chart_animals_unfiltered_3 {
            get {
                return ResourceManager.GetString("chart_animals_unfiltered_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die relative number of lines ähnelt.
        /// </summary>
        internal static string chart_axis_y_lines {
            get {
                return ResourceManager.GetString("chart_axis_y_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die relative time ähnelt.
        /// </summary>
        internal static string chart_axis_y_time {
            get {
                return ResourceManager.GetString("chart_axis_y_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die valid data ähnelt.
        /// </summary>
        internal static string chart_filter_legend_0 {
            get {
                return ResourceManager.GetString("chart_filter_legend_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die threshold filtered ähnelt.
        /// </summary>
        internal static string chart_filter_legend_1 {
            get {
                return ResourceManager.GetString("chart_filter_legend_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die inactivity filtered ähnelt.
        /// </summary>
        internal static string chart_filter_legend_2 {
            get {
                return ResourceManager.GetString("chart_filter_legend_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die slow filtered ähnelt.
        /// </summary>
        internal static string chart_filter_legend_3 {
            get {
                return ResourceManager.GetString("chart_filter_legend_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fast filtered ähnelt.
        /// </summary>
        internal static string chart_filter_legend_4 {
            get {
                return ResourceManager.GetString("chart_filter_legend_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not detected filtered ähnelt.
        /// </summary>
        internal static string chart_filter_legend_5 {
            get {
                return ResourceManager.GetString("chart_filter_legend_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die animal lines threshold ähnelt.
        /// </summary>
        internal static string chart_filter_legend_6 {
            get {
                return ResourceManager.GetString("chart_filter_legend_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resulting data after applying all filter. ähnelt.
        /// </summary>
        internal static string chart_title_animal_afterfilter {
            get {
                return ResourceManager.GetString("chart_title_animal_afterfilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data before applying any filter. ähnelt.
        /// </summary>
        internal static string chart_title_animal_beforefilter {
            get {
                return ResourceManager.GetString("chart_title_animal_beforefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview of applied filters. ähnelt.
        /// </summary>
        internal static string chart_title_filters {
            get {
                return ResourceManager.GetString("chart_title_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Animals ähnelt.
        /// </summary>
        internal static string column_import_animals {
            get {
                return ResourceManager.GetString("column_import_animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Good ähnelt.
        /// </summary>
        internal static string column_import_check {
            get {
                return ResourceManager.GetString("column_import_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicates ähnelt.
        /// </summary>
        internal static string column_import_duplicates {
            get {
                return ResourceManager.GetString("column_import_duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration overall ähnelt.
        /// </summary>
        internal static string column_import_duration {
            get {
                return ResourceManager.GetString("column_import_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File or folder name ähnelt.
        /// </summary>
        internal static string column_import_filename {
            get {
                return ResourceManager.GetString("column_import_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images ähnelt.
        /// </summary>
        internal static string column_import_imagesfound {
            get {
                return ResourceManager.GetString("column_import_imagesfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        internal static string column_import_lines {
            get {
                return ResourceManager.GetString("column_import_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error description ähnelt.
        /// </summary>
        internal static string column_import_problems {
            get {
                return ResourceManager.GetString("column_import_problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time/Datatrack ähnelt.
        /// </summary>
        internal static string column_import_secpertrack {
            get {
                return ResourceManager.GetString("column_import_secpertrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2-circle experiments: ähnelt.
        /// </summary>
        internal static string destination_2circle_header {
            get {
                return ResourceManager.GetString("destination_2circle_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merge the original two lines into one line ähnelt.
        /// </summary>
        internal static string destination_2circle_mergetracks {
            get {
                return ResourceManager.GetString("destination_2circle_mergetracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create combined line charts for inner and outer circle for each animal ähnelt.
        /// </summary>
        internal static string destination_2circle_savecharts_combined {
            get {
                return ResourceManager.GetString("destination_2circle_savecharts_combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create line charts for inner circle for each animal ähnelt.
        /// </summary>
        internal static string destination_2circle_savecharts_inner {
            get {
                return ResourceManager.GetString("destination_2circle_savecharts_inner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create line charts for outer circle for each animal ähnelt.
        /// </summary>
        internal static string destination_2circle_savecharts_outer {
            get {
                return ResourceManager.GetString("destination_2circle_savecharts_outer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save the charts ähnelt.
        /// </summary>
        internal static string destination_charts {
            get {
                return ResourceManager.GetString("destination_charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chart options: ähnelt.
        /// </summary>
        internal static string destination_charts_header {
            get {
                return ResourceManager.GetString("destination_charts_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add additional columns for sums and relative amounts. ähnelt.
        /// </summary>
        internal static string destination_checkbox_addcolumns {
            get {
                return ResourceManager.GetString("destination_checkbox_addcolumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add additional columns for groups ähnelt.
        /// </summary>
        internal static string destination_checkbox_addgroupcolumns {
            get {
                return ResourceManager.GetString("destination_checkbox_addgroupcolumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create subfolder for chart files ähnelt.
        /// </summary>
        internal static string destination_checkbox_chart_subfolders {
            get {
                return ResourceManager.GetString("destination_checkbox_chart_subfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use animal name as X axis value ähnelt.
        /// </summary>
        internal static string destination_checkbox_chart_xaxisrenaming {
            get {
                return ResourceManager.GetString("destination_checkbox_chart_xaxisrenaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merge ZebraLab image files into one ähnelt.
        /// </summary>
        internal static string destination_checkbox_enableimagemerger {
            get {
                return ResourceManager.GetString("destination_checkbox_enableimagemerger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create subfolder for each imported file ähnelt.
        /// </summary>
        internal static string destination_checkbox_file_subfolders {
            get {
                return ResourceManager.GetString("destination_checkbox_file_subfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write filter settings to output file (xlsx-files only). ähnelt.
        /// </summary>
        internal static string destination_checkbox_filterheader {
            get {
                return ResourceManager.GetString("destination_checkbox_filterheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die a) Same folder as the imported file? ähnelt.
        /// </summary>
        internal static string destination_checkbox_importfolder {
            get {
                return ResourceManager.GetString("destination_checkbox_importfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die b) Another folder {0} ähnelt.
        /// </summary>
        internal static string destination_checkbox_otherfolder {
            get {
                return ResourceManager.GetString("destination_checkbox_otherfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite existing files? ähnelt.
        /// </summary>
        internal static string destination_checkbox_overwrite {
            get {
                return ResourceManager.GetString("destination_checkbox_overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use animal counting in Matlab style (vertical) not ZebraLab style (horizontal) ähnelt.
        /// </summary>
        internal static string destination_checkbox_reorderanimals {
            get {
                return ResourceManager.GetString("destination_checkbox_reorderanimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filetype? ähnelt.
        /// </summary>
        internal static string destination_filetype {
            get {
                return ResourceManager.GetString("destination_filetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image merger: ähnelt.
        /// </summary>
        internal static string destination_imagemerger_header {
            get {
                return ResourceManager.GetString("destination_imagemerger_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiple worksheets ähnelt.
        /// </summary>
        internal static string destination_multiworksheet {
            get {
                return ResourceManager.GetString("destination_multiworksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data options: ähnelt.
        /// </summary>
        internal static string destination_options {
            get {
                return ResourceManager.GetString("destination_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Where to save? ähnelt.
        /// </summary>
        internal static string destination_wheretosave {
            get {
                return ResourceManager.GetString("destination_wheretosave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die b) XLS (Microsoft Office 2010) ähnelt.
        /// </summary>
        internal static string destination_xls {
            get {
                return ResourceManager.GetString("destination_xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die a) XLSX (Microsoft Office 2013/2016) ähnelt.
        /// </summary>
        internal static string destination_xlsx {
            get {
                return ResourceManager.GetString("destination_xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorite name? ähnelt.
        /// </summary>
        internal static string favorite_save_header {
            get {
                return ResourceManager.GetString("favorite_save_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name for this favorite. ähnelt.
        /// </summary>
        internal static string favorite_save_question {
            get {
                return ResourceManager.GetString("favorite_save_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 5. Lines left (%): ähnelt.
        /// </summary>
        internal static string filter_animallines {
            get {
                return ResourceManager.GetString("filter_animallines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recommended: Remove {0} ({1}%) line duplicates. ähnelt.
        /// </summary>
        internal static string filter_checkbox_duplicates {
            get {
                return ResourceManager.GetString("filter_checkbox_duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove {0} ({1}%) lines with an invalid duration sum. ähnelt.
        /// </summary>
        internal static string filter_checkbox_invalidsum {
            get {
                return ResourceManager.GetString("filter_checkbox_invalidsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4. Not detected (emptydur%): ähnelt.
        /// </summary>
        internal static string filter_empty {
            get {
                return ResourceManager.GetString("filter_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2. Fast speed (lardur%): ähnelt.
        /// </summary>
        internal static string filter_fast {
            get {
                return ResourceManager.GetString("filter_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt; fish &lt; ähnelt.
        /// </summary>
        internal static string filter_fish {
            get {
                return ResourceManager.GetString("filter_fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3. Inactive (inadur%): ähnelt.
        /// </summary>
        internal static string filter_inactive {
            get {
                return ResourceManager.GetString("filter_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die max ähnelt.
        /// </summary>
        internal static string filter_max {
            get {
                return ResourceManager.GetString("filter_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die min ähnelt.
        /// </summary>
        internal static string filter_min {
            get {
                return ResourceManager.GetString("filter_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1. Slow speed (smldur%): ähnelt.
        /// </summary>
        internal static string filter_slow {
            get {
                return ResourceManager.GetString("filter_slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group ähnelt.
        /// </summary>
        internal static string grouping_celltitle_group {
            get {
                return ResourceManager.GetString("grouping_celltitle_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiple files provided.
        ///Please select file to change table: ähnelt.
        /// </summary>
        internal static string grouping_multifiles_info {
            get {
                return ResourceManager.GetString("grouping_multifiles_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group 0: ähnelt.
        /// </summary>
        internal static string groups_renaming_group0 {
            get {
                return ResourceManager.GetString("groups_renaming_group0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group 1: ähnelt.
        /// </summary>
        internal static string groups_renaming_group1 {
            get {
                return ResourceManager.GetString("groups_renaming_group1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group 2: ähnelt.
        /// </summary>
        internal static string groups_renaming_group2 {
            get {
                return ResourceManager.GetString("groups_renaming_group2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group 3: ähnelt.
        /// </summary>
        internal static string groups_renaming_group3 {
            get {
                return ResourceManager.GetString("groups_renaming_group3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group 4: ähnelt.
        /// </summary>
        internal static string groups_renaming_group4 {
            get {
                return ResourceManager.GetString("groups_renaming_group4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group 5: ähnelt.
        /// </summary>
        internal static string groups_renaming_group5 {
            get {
                return ResourceManager.GetString("groups_renaming_group5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group 6: ähnelt.
        /// </summary>
        internal static string groups_renaming_group6 {
            get {
                return ResourceManager.GetString("groups_renaming_group6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group 7: ähnelt.
        /// </summary>
        internal static string groups_renaming_group7 {
            get {
                return ResourceManager.GetString("groups_renaming_group7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group 8: ähnelt.
        /// </summary>
        internal static string groups_renaming_group8 {
            get {
                return ResourceManager.GetString("groups_renaming_group8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group 9: ähnelt.
        /// </summary>
        internal static string groups_renaming_group9 {
            get {
                return ResourceManager.GetString("groups_renaming_group9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use the following boxes to rename your animal groups. If empty, the group number will be used. ähnelt.
        /// </summary>
        internal static string groups_renaming_header {
            get {
                return ResourceManager.GetString("groups_renaming_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZLab-Fileconverter ähnelt.
        /// </summary>
        internal static string header_converter {
            get {
                return ResourceManager.GetString("header_converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorites ähnelt.
        /// </summary>
        internal static string menu_favorites {
            get {
                return ResourceManager.GetString("menu_favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load #&amp;1 - {0} ähnelt.
        /// </summary>
        internal static string menu_favorites_load_f1 {
            get {
                return ResourceManager.GetString("menu_favorites_load_f1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load #&amp;2 - {0} ähnelt.
        /// </summary>
        internal static string menu_favorites_load_f2 {
            get {
                return ResourceManager.GetString("menu_favorites_load_f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load #&amp;3 - {0} ähnelt.
        /// </summary>
        internal static string menu_favorites_load_f3 {
            get {
                return ResourceManager.GetString("menu_favorites_load_f3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as #1 ähnelt.
        /// </summary>
        internal static string menu_favorites_save_f1 {
            get {
                return ResourceManager.GetString("menu_favorites_save_f1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as #2 ähnelt.
        /// </summary>
        internal static string menu_favorites_save_f2 {
            get {
                return ResourceManager.GetString("menu_favorites_save_f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as #3 ähnelt.
        /// </summary>
        internal static string menu_favorites_save_f3 {
            get {
                return ResourceManager.GetString("menu_favorites_save_f3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;File ähnelt.
        /// </summary>
        internal static string menu_file {
            get {
                return ResourceManager.GetString("menu_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Exit ähnelt.
        /// </summary>
        internal static string menu_file_exit {
            get {
                return ResourceManager.GetString("menu_file_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Settings ähnelt.
        /// </summary>
        internal static string menu_file_settings {
            get {
                return ResourceManager.GetString("menu_file_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File handling ähnelt.
        /// </summary>
        internal static string menu_filehandling {
            get {
                return ResourceManager.GetString("menu_filehandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move down ähnelt.
        /// </summary>
        internal static string menu_filehandling_entrydown {
            get {
                return ResourceManager.GetString("menu_filehandling_entrydown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move up ähnelt.
        /// </summary>
        internal static string menu_filehandling_entryup {
            get {
                return ResourceManager.GetString("menu_filehandling_entryup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable/Disable ähnelt.
        /// </summary>
        internal static string menu_filehandling_removeentry {
            get {
                return ResourceManager.GetString("menu_filehandling_removeentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Grouping ähnelt.
        /// </summary>
        internal static string menu_grouping {
            get {
                return ResourceManager.GetString("menu_grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One group per 2 columns ähnelt.
        /// </summary>
        internal static string menu_grouping_2col {
            get {
                return ResourceManager.GetString("menu_grouping_2col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One group per 3 columns ähnelt.
        /// </summary>
        internal static string menu_grouping_3col {
            get {
                return ResourceManager.GetString("menu_grouping_3col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One group per 4 columns ähnelt.
        /// </summary>
        internal static string menu_grouping_4col {
            get {
                return ResourceManager.GetString("menu_grouping_4col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Rename groups ähnelt.
        /// </summary>
        internal static string menu_grouping_renameutility {
            get {
                return ResourceManager.GetString("menu_grouping_renameutility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Help ähnelt.
        /// </summary>
        internal static string menu_help {
            get {
                return ResourceManager.GetString("menu_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;About ähnelt.
        /// </summary>
        internal static string menu_help_about {
            get {
                return ResourceManager.GetString("menu_help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Help &amp;&amp; Support ähnelt.
        /// </summary>
        internal static string menu_help_support {
            get {
                return ResourceManager.GetString("menu_help_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done. I&apos;ve created {0} cleaned data files and {1} chart images. ähnelt.
        /// </summary>
        internal static string result_export_done {
            get {
                return ResourceManager.GetString("result_export_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancelled by user. ähnelt.
        /// </summary>
        internal static string result_export_error_cancelled {
            get {
                return ResourceManager.GetString("result_export_error_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t create output file: {0}:\r\n {1} ähnelt.
        /// </summary>
        internal static string result_export_error_createfile {
            get {
                return ResourceManager.GetString("result_export_error_createfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite file? ähnelt.
        /// </summary>
        internal static string result_export_overwrite_header {
            get {
                return ResourceManager.GetString("result_export_overwrite_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file {0} already exists. Overwrite it? ähnelt.
        /// </summary>
        internal static string result_export_overwrite_question {
            get {
                return ResourceManager.GetString("result_export_overwrite_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creating output files. Please wait. ähnelt.
        /// </summary>
        internal static string result_exporting {
            get {
                return ResourceManager.GetString("result_exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, I got no valid files. Please try again. ähnelt.
        /// </summary>
        internal static string result_import_error_nofiles {
            get {
                return ResourceManager.GetString("result_import_error_nofiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file {0} could not be imported due to the following error: {1} ähnelt.
        /// </summary>
        internal static string result_import_error_other {
            get {
                return ResourceManager.GetString("result_import_error_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die animal ähnelt.
        /// </summary>
        internal static string result_table_col_animal {
            get {
                return ResourceManager.GetString("result_table_col_animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die lines left ähnelt.
        /// </summary>
        internal static string result_table_col_linesleft {
            get {
                return ResourceManager.GetString("result_table_col_linesleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die lines removed ähnelt.
        /// </summary>
        internal static string result_table_col_linesremoved {
            get {
                return ResourceManager.GetString("result_table_col_linesremoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die lines total ähnelt.
        /// </summary>
        internal static string result_table_col_linestotal {
            get {
                return ResourceManager.GetString("result_table_col_linestotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die well ähnelt.
        /// </summary>
        internal static string result_table_col_well {
            get {
                return ResourceManager.GetString("result_table_col_well", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die upscale result chart to 100% ähnelt.
        /// </summary>
        internal static string result_upscalechart {
            get {
                return ResourceManager.GetString("result_upscalechart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zlab converter settings ähnelt.
        /// </summary>
        internal static string settings_header {
            get {
                return ResourceManager.GetString("settings_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        internal static string settings_langgroup_de {
            get {
                return ResourceManager.GetString("settings_langgroup_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System default language: {0} ähnelt.
        /// </summary>
        internal static string settings_langgroup_default {
            get {
                return ResourceManager.GetString("settings_langgroup_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        internal static string settings_langgroup_en {
            get {
                return ResourceManager.GetString("settings_langgroup_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spanish ähnelt.
        /// </summary>
        internal static string settings_langgroup_es {
            get {
                return ResourceManager.GetString("settings_langgroup_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language settings ähnelt.
        /// </summary>
        internal static string settings_langgroup_header {
            get {
                return ResourceManager.GetString("settings_langgroup_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not all words may be translated right now. Always the fallback language is english. To support the translation process, please visit software.fuchs.pub/Zlab-Analyzer. ähnelt.
        /// </summary>
        internal static string settings_langgroup_subinfo {
            get {
                return ResourceManager.GetString("settings_langgroup_subinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2 circle preview ähnelt.
        /// </summary>
        internal static string tabcontrol_2circle {
            get {
                return ResourceManager.GetString("tabcontrol_2circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die basic settings ähnelt.
        /// </summary>
        internal static string tabcontrol_basic {
            get {
                return ResourceManager.GetString("tabcontrol_basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die destination ähnelt.
        /// </summary>
        internal static string tabcontrol_destination {
            get {
                return ResourceManager.GetString("tabcontrol_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die grouping ähnelt.
        /// </summary>
        internal static string tabcontrol_grouping {
            get {
                return ResourceManager.GetString("tabcontrol_grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die import notifications ähnelt.
        /// </summary>
        internal static string tabcontrol_import {
            get {
                return ResourceManager.GetString("tabcontrol_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die result ähnelt.
        /// </summary>
        internal static string tabcontrol_result {
            get {
                return ResourceManager.GetString("tabcontrol_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die filter thresholds ähnelt.
        /// </summary>
        internal static string tabcontrol_threshold {
            get {
                return ResourceManager.GetString("tabcontrol_threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you check the box at the bottom of this window, the conversion will be done automatically, after dropping the file, using your last filter settings. ähnelt.
        /// </summary>
        internal static string usage_addition {
            get {
                return ResourceManager.GetString("usage_addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic processing with last settings. ähnelt.
        /// </summary>
        internal static string usage_autostart {
            get {
                return ResourceManager.GetString("usage_autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usage of this converter is simple:
        ///
        ///1. Drop an xls file from the ZebraLab export on this window (or a folder with such a file).
        ///
        ///2. Apply your settings to filter your data.
        ///
        ///3. Click on &quot;Create Export&quot; to create a new and clean file.
        ///
        ///
        ///Your filter settings will be saved automatic for the next usage. ähnelt.
        /// </summary>
        internal static string usage_base {
            get {
                return ResourceManager.GetString("usage_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait, I&apos;m checking the dropped file. ähnelt.
        /// </summary>
        internal static string usage_checkingfile {
            get {
                return ResourceManager.GetString("usage_checkingfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait, I&apos;m checking the dropped files. ähnelt.
        /// </summary>
        internal static string usage_checkingfiles {
            get {
                return ResourceManager.GetString("usage_checkingfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usage of the basic settings:
        /// 
        ///   Check the boxes you need.
        ///
        ///-----------------------------------------------------------------------------------------
        ///
        ///Results:
        ///
        ///   1. Remove line duplicates: The xls files from ZebraLab contains for each animal and record a duplicate line, sometimes with different values. Those duplicate lines will be filtered out of the result file, when the box is checked. Any chart in this program will use this setting no matter if you have checked it or not.
        ///
        ///   2. Remove lines wit [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string usage_tab1_basics {
            get {
                return ResourceManager.GetString("usage_tab1_basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usage of the filter thresholds:
        ///    Apply numeric threshold values, as needed.
        ///-----------------------------------------------------------------------------------------
        ///    With this boxes you can apply thresholds to your data. Any line (from source data file) with a relative duration time below the min or above the maximum is truncated. The lines won&apos;t appear in the exported Excel file. 
        ///   The last box &quot;Lines left&quot; means, that at least this relative number of lines (from the source data file, checked  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string usage_tab2_thresholds {
            get {
                return ResourceManager.GetString("usage_tab2_thresholds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string usage_tab3_result {
            get {
                return ResourceManager.GetString("usage_tab3_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string usage_tab4_destination {
            get {
                return ResourceManager.GetString("usage_tab4_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usage of the grouping table:
        ///   If you want to group your animals, select them by clicking on the header or on the animal and then press the buttons 0 to 9 to assign one of the ten possible groups. 0 is always the default group.
        ///
        ///   You may also use the shortcuts Ctrl+2, Ctrl+3 or Ctrl+4 to apply prepared templates: the animals are grouped and each group contains 2, 3 or 4 columns.
        ///   You can use the renaming utilitiy (accessible by Ctrl+R) to assign custom names to your groups. If no name is assigned,  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string usage_tab5_grouping {
            get {
                return ResourceManager.GetString("usage_tab5_grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zlab-Fileconverter cleaned ZebraLab data file from {0}. ähnelt.
        /// </summary>
        internal static string xlsx_header_description {
            get {
                return ResourceManager.GetString("xlsx_header_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die applied filters max values: ähnelt.
        /// </summary>
        internal static string xlsx_header_filtermax {
            get {
                return ResourceManager.GetString("xlsx_header_filtermax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die applied filters min values: ähnelt.
        /// </summary>
        internal static string xlsx_header_filtermin {
            get {
                return ResourceManager.GetString("xlsx_header_filtermin", resourceCulture);
            }
        }
    }
}
